(a)
x <- rnorm(100)
eps <- rnorm(100)
(b)
y <- 6 + 1*x + 4*x^2 - 1*x^3 + eps
(c)

library(leaps)
data.full <- data.frame(y,x)
regfit.full <- regsubsets(y~ poly(x,10), data = data.full, nvmax = 10)
reg.summary <- summary(regfit.full)
par(mfrow = c(2, 2))
plot(reg.summary$cp, xlab = "Number of variables", ylab = "C_p", type = "l")
points(which.min(reg.summary$cp), reg.summary$cp[which.min(reg.summary$cp)], col = "red", cex = 2, pch = 20)
plot(reg.summary$bic, xlab = "Number of variables", ylab = "BIC", type = "l")
points(which.min(reg.summary$bic), reg.summary$bic[which.min(reg.summary$bic)], col = "red", cex = 2, pch = 20)
plot(reg.summary$adjr2, xlab = "Number of variables", ylab = "Adjusted R^2", type = "l")
points(which.max(reg.summary$adjr2), reg.summary$adjr2[which.max(reg.summary$adjr2)], col = "red", cex = 2, pch = 20)
coef(regfit.full, which.max(reg.summary$adjr2))
coef(regfit.full, which.min(reg.summary$cp))
coef(regfit.full, which.min(reg.summary$bic)
cbind(reg.summary$which , adjr2=reg.summary$adjr2 , cp=reg.summary$cp , bic=reg.summary$bic)

#q <- as.vector(rowSums(reg$which))
#q
#plot(q,reg$cp)
#abline(0,b=1)

(d)

regfit.fwd <- regsubsets(y ~ poly(x,10), data = data.full, nvmax = 10, method = "forward")
reg.summary.fwd <- summary(regfit.fwd)
par(mfrow = c(2, 2))
plot(reg.summary.fwd$cp, xlab = "Number of variables", ylab = "C_p", type = "l")
points(which.min(reg.summary.fwd$cp), reg.summary.fwd$cp[which.min(reg.summary.fwd$cp)], col = "red", cex = 2, pch = 20)
plot(reg.summary.fwd$bic, xlab = "Number of variables", ylab = "BIC", type = "l")
points(which.min(reg.summary.fwd$bic), reg.summary.fwd$bic[which.min(reg.summary.fwd$bic)], col = "red", cex = 2, pch = 20)
plot(reg.summary.fwd$adjr2, xlab = "Number of variables", ylab = "Adjusted R^2", type = "l")
points(which.max(reg.summary.fwd$adjr2), reg.summary.fwd$adjr2[which.max(reg.summary.fwd$adjr2)], col = "red", cex = 2, pch = 20)
mtext("Plots of C_p, BIC and adjusted R^2 for forward stepwise selection", side = 3, line = -2, outer = TRUE)
coef(regfit.fwd, which.max(reg.summary.fwd$adjr2))
coef(regfit.full, which.min(reg.summary.fwd$cp))
coef(regfit.full, which.min(reg.summary.fwd$bic))
cbind(reg.summary.fwd$which , adjr2=reg.summary.fwd$adjr2 , cp=reg.summary.fwd$cp , bic=reg.summary.fwd$bic)

regfit.bwd <- regsubsets(y~ poly(x,10), data = data.full, nvmax = 10, method = "backward")
reg.summary.bwd <- summary(regfit.bwd)
par(mfrow = c(2, 2))
plot(reg.summary.bwd$cp, xlab = "Number of variables", ylab = "C_p", type = "l")
points(which.min(reg.summary.bwd$cp), reg.summary.bwd$cp[which.min(reg.summary.bwd$cp)], col = "red", cex = 2, pch = 20)
plot(reg.summary.bwd$bic, xlab = "Number of variables", ylab = "BIC", type = "l")
points(which.min(reg.summary.bwd$bic), reg.summary.bwd$bic[which.min(reg.summary.bwd$bic)], col = "red", cex = 2, pch = 20)
plot(reg.summary.bwd$adjr2, xlab = "Number of variables", ylab = "Adjusted R^2", type = "l")
points(which.max(reg.summary.bwd$adjr2), reg.summary.bwd$adjr2[which.max(reg.summary.bwd$adjr2)], col = "red", cex = 2, pch = 20)
mtext("Plots of C_p, BIC and adjusted R^2 for backward stepwise selection", side = 3, line = -2, outer = TRUE)
coef(regfit.bwd, which.max(reg.summary.bwd$adjr2))
coef(regfit.full, which.min(reg.summary.bwd$cp))
coef(regfit.full, which.min(reg.summary.bwd$bic))
cbind(reg.summary.bwd$which , adjr2=reg.summary.bwd$adjr2 , cp=reg.summary.bwd$cp , bic=reg.summary.bwd$bic)

(e)
fit.pcr <- pcr(Apps ~ ., data = College.train, scale = TRUE, validation = "CV")
validationplot(fit.pcr, val.type = "MSEP")
